### ISSUE TITLE
Hi, is there a way to build this from source?

### ISSUE THREAD

**Issue by Aryagm** [Goel25/ClonePilotExtension#1]

**Comment by leognon** [comment]
Hello Aryagm, Thanks for asking!

It should be possible. VSCode has a [guide](https://code.visualstudio.com/api/get-started/your-first-extension) to how to make an extension. Instead of starting from scratch, you can clone this repo and run `npm install` to install the dependencies.  From VSCode, you can then build and run the extension which will open up a development version of vscode with your version of the extension running.

If you want to use a custom version of this extension on normal vscode (without running the development version), I think you'll have to publish it as an extension (there may be an easier way). For that, [this article](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) is helpful.

I would also recommend watching [this video](https://youtu.be/q5V4T3o3CXE). It was very useful for me and helped with the setup and publishing.

Let me know if you have any troubles or questions!

**Comment by Aryagm** [comment]
Hi,

Thanks for your reply! Was able to do it!

I'm currently working on a project similar to what you did (a bit more serious though :)). If you have some free time and want to contribute, please let me know, we need contributors like you!

Thanks,
Arya

**Comment by leognon** [comment]
I'm glad I could help! I'm quite busy with other projects right now, but I could check out what you're working on. Is it on your github page? I don't think I see it.

**Comment by Aryagm** [comment]
Hi,

The repo is under an organization, you can find it here: https://github.com/DeepGenX/CodeGenX

We are actually building an Open-Source version of GitHub Copilot using a version of GPT-J fine-tuned on code. The fine-tuning of the model is currently under process. 

We do not have people who have worked on VS Code extensions, so we can really use some help from you (Even a couple of hours of help would be great)!

If you are interested, feel free to join our discord here: https://discord.gg/WPwqSkrF

Thanks,
Arya

**Comment by leognon** [comment]
Wow, this looks very interesting! Hopefully my code will be enough to get you started but if I have some free time I can look into it. Good luck 😄
